// ┌─────────────────────────────────────────────────────────────┐
// │ Concierge Product — Timeline API Client (Wave 3 Enhancements)│
// │ Consumes the Timeline Engine REST API.                      │
// └─────────────────────────────────────────────────────────────┘

import { tokenStore } from "./patient-api";

const API_BASE = import.meta.env.VITE_API_BASE ?? "";

// ── Authenticated fetch helper ────────────────────────────

async function authFetch(input: RequestInfo, init?: RequestInit): Promise<Response> {
  const token = tokenStore.getAccessToken();
  const headers: Record<string, string> = {
    ...(init?.headers as Record<string, string>),
  };
  if (token) {
    headers["Authorization"] = `Bearer ${token}`;
  }
  return fetch(input, { ...init, headers });
}

// ═══════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════

export type IvfStage =
  | "registration"
  | "consultation"
  | "treatment_plan"
  | "ivf_cycle"
  | "retrieval"
  | "transfer"
  | "follow_up"
  | "success";

export interface StageStatus {
  stage: IvfStage;
  label: string;
  status: "pending" | "active" | "completed" | "skipped";
  enteredAt: string | null;
  completedAt: string | null;
  expectedDurationDays: number;
  expectedCompletionDate: string | null;
  actualDurationDays: number | null;
  notes: string;
}

export type MilestoneType =
  | "registration"
  | "consultation"
  | "treatment_plan"
  | "ivf_cycle_start"
  | "retrieval"
  | "transfer"
  | "pregnancy_test"
  | "follow_up"
  | "success"
  | "custom";

export interface Milestone {
  id: string;
  type: MilestoneType;
  title: string;
  description: string;
  stage: IvfStage;
  date: string;
  achieved: boolean;
  achievedAt: string | null;
  expectedDate: string | null;
  autoGenerated: boolean;
}

export type EventCategory =
  | "stage_change"
  | "milestone_achieved"
  | "task_completed"
  | "appointment_scheduled"
  | "note_added"
  | "system";

export interface TimelineEvent {
  id: string;
  timestamp: string;
  category: EventCategory;
  title: string;
  description: string;
  refId: string | null;
  refType: string | null;
}

export interface ProgressSummary {
  overallPercent: number;
  stagesCompleted: number;
  stagesTotal: number;
  currentStage: string | null;
  milestonesAchieved: number;
  milestonesTotal: number;
  estimatedRemainingDays: number | null;
}

export interface ExpectedDateInfo {
  stage: IvfStage;
  label: string;
  estimatedStartDate: string | null;
  estimatedCompletionDate: string | null;
  typicalDurationDays: number;
  estimateType: "default" | "adjusted";
}

export interface FullTimeline {
  patientId: string;
  stages: StageStatus[];
  milestones: Milestone[];
  events: TimelineEvent[];
  progress: ProgressSummary;
  expectedDates: ExpectedDateInfo[];
  updatedAt: string;
  createdAt: string;
}

// ── Legacy types (backward compat) ────────────────────────

export interface CarePlanPhase {
  id: string;
  name: string;
  description: string;
  order: number;
  status: "not_started" | "in_progress" | "completed";
  startDate: string | null;
  completedDate: string | null;
  tasks: string[];
}

export interface Task {
  id: string;
  title: string;
  description: string;
  phaseId: string;
  status: "pending" | "in_progress" | "completed";
  dueDate: string | null;
  completedAt: string | null;
  createdAt: string;
}

// ═══════════════════════════════════════════════════════════════
// Full Timeline
// ═══════════════════════════════════════════════════════════════

export async function getTimeline(): Promise<FullTimeline> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline`);
  if (!res.ok) throw new Error(`Failed to fetch timeline: ${res.status}`);
  const data: { timeline: FullTimeline } = await res.json();
  return data.timeline;
}

// ═══════════════════════════════════════════════════════════════
// Stages
// ═══════════════════════════════════════════════════════════════

export async function getStages(): Promise<StageStatus[]> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/stages`);
  if (!res.ok) throw new Error(`Failed to fetch stages: ${res.status}`);
  const data: { stages: StageStatus[] } = await res.json();
  return data.stages;
}

export async function getCurrentStage(): Promise<{ stage: StageStatus | null; message?: string }> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/stages/current`);
  if (!res.ok) throw new Error(`Failed to fetch current stage: ${res.status}`);
  return res.json();
}

export async function advanceStage(notes?: string): Promise<StageStatus> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/stages/advance`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: notes ? JSON.stringify({ notes }) : undefined,
  });
  if (!res.ok) {
    const data = await res.json().catch(() => ({}));
    throw new Error(data.error || `Failed to advance stage: ${res.status}`);
  }
  const data: { stage: StageStatus } = await res.json();
  return data.stage;
}

// ═══════════════════════════════════════════════════════════════
// Milestones
// ═══════════════════════════════════════════════════════════════

export async function getMilestones(filters?: { achieved?: boolean }): Promise<Milestone[]> {
  const params = new URLSearchParams();
  if (filters?.achieved !== undefined) params.set("achieved", String(filters.achieved));
  const qs = params.toString();
  const res = await authFetch(`${API_BASE}/api/v1/timeline/milestones${qs ? `?${qs}` : ""}`);
  if (!res.ok) throw new Error(`Failed to fetch milestones: ${res.status}`);
  const data: { milestones: Milestone[] } = await res.json();
  return data.milestones;
}

export async function getMilestone(id: string): Promise<Milestone> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/milestones/${id}`);
  if (!res.ok) throw new Error(`Failed to fetch milestone: ${res.status}`);
  const data: { milestone: Milestone } = await res.json();
  return data.milestone;
}

export async function createMilestone(
  type: string,
  title: string,
  description: string,
  expectedDate?: string,
): Promise<Milestone> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/milestones`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ type, title, description, expectedDate }),
  });
  if (!res.ok) throw new Error(`Failed to create milestone: ${res.status}`);
  const data: { milestone: Milestone } = await res.json();
  return data.milestone;
}

export async function achieveMilestone(id: string): Promise<Milestone> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/milestones/${id}/achieve`, {
    method: "POST",
  });
  if (!res.ok) throw new Error(`Failed to achieve milestone: ${res.status}`);
  const data: { milestone: Milestone } = await res.json();
  return data.milestone;
}

// ═══════════════════════════════════════════════════════════════
// Events
// ═══════════════════════════════════════════════════════════════

export async function getEvents(category?: EventCategory): Promise<TimelineEvent[]> {
  const params = new URLSearchParams();
  if (category) params.set("category", category);
  const qs = params.toString();
  const res = await authFetch(`${API_BASE}/api/v1/timeline/events${qs ? `?${qs}` : ""}`);
  if (!res.ok) throw new Error(`Failed to fetch events: ${res.status}`);
  const data: { events: TimelineEvent[] } = await res.json();
  return data.events;
}

// ═══════════════════════════════════════════════════════════════
// Progress
// ═══════════════════════════════════════════════════════════════

export async function getProgress(): Promise<ProgressSummary> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/progress`);
  if (!res.ok) throw new Error(`Failed to fetch progress: ${res.status}`);
  const data: { progress: ProgressSummary } = await res.json();
  return data.progress;
}

// ═══════════════════════════════════════════════════════════════
// Expected Dates
// ═══════════════════════════════════════════════════════════════

export async function getExpectedDates(): Promise<ExpectedDateInfo[]> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/dates`);
  if (!res.ok) throw new Error(`Failed to fetch expected dates: ${res.status}`);
  const data: { expectedDates: ExpectedDateInfo[] } = await res.json();
  return data.expectedDates;
}

// ═══════════════════════════════════════════════════════════════
// Legacy: Phases (backward compat)
// ═══════════════════════════════════════════════════════════════

export async function getPhases(): Promise<{ phases: CarePlanPhase[]; currentPhase: string | null; progressPercent: number }> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/phases`);
  if (!res.ok) throw new Error(`Failed to fetch phases: ${res.status}`);
  return res.json();
}

// ═══════════════════════════════════════════════════════════════
// Legacy: Tasks (backward compat)
// ═══════════════════════════════════════════════════════════════

export async function getTasks(filters?: { status?: string; phaseId?: string }): Promise<Task[]> {
  const params = new URLSearchParams();
  if (filters?.status) params.set("status", filters.status);
  if (filters?.phaseId) params.set("phaseId", filters.phaseId);
  const qs = params.toString();
  const res = await authFetch(`${API_BASE}/api/v1/timeline/tasks${qs ? `?${qs}` : ""}`);
  if (!res.ok) throw new Error(`Failed to fetch tasks: ${res.status}`);
  const data: { tasks: Task[] } = await res.json();
  return data.tasks;
}

export async function getTask(id: string): Promise<Task> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/tasks/${id}`);
  if (!res.ok) throw new Error(`Failed to fetch task: ${res.status}`);
  const data: { task: Task } = await res.json();
  return data.task;
}

export async function updateTask(id: string, updates: Partial<{ status: string; title: string; description: string; dueDate: string }>): Promise<Task> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/tasks/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(updates),
  });
  if (!res.ok) throw new Error(`Failed to update task: ${res.status}`);
  const data: { task: Task } = await res.json();
  return data.task;
}