// ┌─────────────────────────────────────────────────────────────┐
// │ Concierge Product — Timeline API Client (Wave 3)             │
// │ Consumes the Timeline Engine REST API.                      │
// └─────────────────────────────────────────────────────────────┘

import { tokenStore } from "./patient-api";

const API_BASE = import.meta.env.VITE_API_BASE ?? "";

async function authFetch(input: RequestInfo, init?: RequestInit): Promise<Response> {
  const token = tokenStore.getAccessToken();
  const headers = new Headers(init?.headers);
  if (token) {
    headers.set("Authorization", `Bearer ${token}`);
  }
  headers.set("Content-Type", "application/json");
  return fetch(input, { ...init, headers });
}

// ═══════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════

export type IvfStage =
  | "registration"
  | "consultation"
  | "treatment_plan"
  | "ivf_cycle"
  | "retrieval"
  | "transfer"
  | "follow_up"
  | "success";

export interface StageStatus {
  stage: IvfStage;
  label: string;
  status: "pending" | "active" | "completed" | "skipped";
  enteredAt: string | null;
  completedAt: string | null;
  expectedDurationDays: number;
  expectedCompletionDate: string | null;
  actualDurationDays: number | null;
  notes: string;
}

export type MilestoneType =
  | "registration"
  | "consultation"
  | "treatment_plan"
  | "ivf_cycle_start"
  | "retrieval"
  | "transfer"
  | "pregnancy_test"
  | "follow_up"
  | "success"
  | "custom";

export interface Milestone {
  id: string;
  type: MilestoneType;
  title: string;
  description: string;
  stage: IvfStage;
  date: string;
  achieved: boolean;
  achievedAt: string | null;
  expectedDate: string | null;
  autoGenerated: boolean;
}

export type EventCategory =
  | "stage_change"
  | "milestone_achieved"
  | "task_completed"
  | "appointment_scheduled"
  | "note_added"
  | "system";

export interface TimelineEvent {
  id: string;
  timestamp: string;
  category: EventCategory;
  title: string;
  description: string;
  refId: string | null;
  refType: "stage" | "milestone" | null;
}

export interface ProgressSummary {
  overallPercent: number;
  stagesCompleted: number;
  stagesTotal: number;
  currentStage: IvfStage | null;
  milestonesAchieved: number;
  milestonesTotal: number;
  estimatedRemainingDays: number | null;
}

export interface ExpectedDateInfo {
  stage: IvfStage;
  label: string;
  estimatedStartDate: string | null;
  estimatedCompletionDate: string | null;
}

export interface FullTimeline {
  stages: StageStatus[];
  milestones: Milestone[];
  events: TimelineEvent[];
  progress: ProgressSummary;
  expectedDates: ExpectedDateInfo[];
}

// ═══════════════════════════════════════════════════════════
// Legacy CarePlan Types (for backward compat)
// ═══════════════════════════════════════════════════════════

export interface CarePlanPhase {
  id: string;
  name: string;
  description: string;
  order: number;
  status: "not_started" | "in_progress" | "completed";
  startDate: string | null;
  completedDate: string | null;
  tasks: string[];
}

export interface Task {
  id: string;
  title: string;
  description: string;
  phaseId: string;
  status: "pending" | "in_progress" | "completed";
  dueDate: string | null;
  completedAt: string | null;
  createdAt: string;
}

// ═══════════════════════════════════════════════════════════
// API Client
// ═══════════════════════════════════════════════════════════

export async function getTimeline(): Promise<FullTimeline> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline`);
  if (!res.ok) throw new Error(`Failed to fetch timeline: ${res.status}`);
  const data = (await res.json()) as { timeline: FullTimeline };
  return data.timeline;
}

export async function getStages(): Promise<StageStatus[]> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/stages`);
  if (!res.ok) throw new Error(`Failed to fetch stages: ${res.status}`);
  const data = (await res.json()) as { stages: StageStatus[] };
  return data.stages;
}

export async function getStage(stage: IvfStage): Promise<StageStatus | null> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/stages/${stage}`);
  if (!res.ok) throw new Error(`Failed to fetch stage: ${res.status}`);
  const data = (await res.json()) as { stage: StageStatus };
  return data.stage;
}

export async function advanceStage(notes: string = ""): Promise<StageStatus> {
  const res = await authFetch(
    `${API_BASE}/api/v1/timeline/stages/advance`,
    {
      method: "PATCH",
      body: JSON.stringify({ notes }),
    },
  );
  if (!res.ok) throw new Error(`Failed to advance stage: ${res.status}`);
  const data = (await res.json()) as { stage: StageStatus };
  return data.stage;
}

export async function getMilestones(): Promise<Milestone[]> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/milestones`);
  if (!res.ok) throw new Error(`Failed to fetch milestones: ${res.status}`);
  const data = (await res.json()) as { milestones: Milestone[] };
  return data.milestones;
}

export async function getMilestone(id: string): Promise<Milestone | null> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/milestones/${id}`);
  if (!res.ok) throw new Error(`Failed to fetch milestone: ${res.status}`);
  const data = (await res.json()) as { milestone: Milestone };
  return data.milestone;
}

export async function achieveMilestone(id: string): Promise<Milestone> {
  const res = await authFetch(
    `${API_BASE}/api/v1/timeline/milestones/${id}/achieve`,
    { method: "PATCH" },
  );
  if (!res.ok) throw new Error(`Failed to achieve milestone: ${res.status}`);
  const data = (await res.json()) as { milestone: Milestone };
  return data.milestone;
}

export async function getEvents(): Promise<TimelineEvent[]> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/events`);
  if (!res.ok) throw new Error(`Failed to fetch events: ${res.status}`);
  const data = (await res.json()) as { events: TimelineEvent[] };
  return data.events;
}

export async function getProgress(): Promise<ProgressSummary> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/progress`);
  if (!res.ok) throw new Error(`Failed to fetch progress: ${res.status}`);
  const data = (await res.json()) as { progress: ProgressSummary };
  return data.progress;
}

export async function getExpectedDates(): Promise<ExpectedDateInfo[]> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/expected-dates`);
  if (!res.ok) throw new Error(`Failed to fetch expected dates: ${res.status}`);
  const data = (await res.json()) as { expectedDates: ExpectedDateInfo[] };
  return data.expectedDates;
}

// ── Legacy CarePlan API (backward compat) ──────────────

export async function getPhases(): Promise<{ phases: CarePlanPhase[]; currentPhase: string | null; progressPercent: number }> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/phases`);
  if (!res.ok) throw new Error(`Failed to fetch phases: ${res.status}`);
  return res.json();
}

export async function getTasks(filters?: { status?: string; phaseId?: string }): Promise<Task[]> {
  const params = new URLSearchParams();
  if (filters?.status) params.set("status", filters.status);
  if (filters?.phaseId) params.set("phaseId", filters.phaseId);
  const qs = params.toString();
  const res = await authFetch(`${API_BASE}/api/v1/timeline/tasks${qs ? `?${qs}` : ""}`);
  if (!res.ok) throw new Error(`Failed to fetch tasks: ${res.status}`);
  const data = (await res.json()) as { tasks: Task[] };
  return data.tasks;
}

export async function getTask(id: string): Promise<Task> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/tasks/${id}`);
  if (!res.ok) throw new Error(`Failed to fetch task: ${res.status}`);
  const data = (await res.json()) as { task: Task };
  return data.task;
}

export async function updateTask(id: string, updates: Partial<{ status: string; title: string; description: string; dueDate: string }>): Promise<Task> {
  const res = await authFetch(`${API_BASE}/api/v1/timeline/tasks/${id}`, {
    method: "PATCH",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(updates),
  });
  if (!res.ok) throw new Error(`Failed to update task: ${res.status}`);
  const data = (await res.json()) as { task: Task };
  return data.task;
}
