// ┌─────────────────────────────────────────────────────────────┐
// │ D1 Timeline Engine                                           │
// │ Wave 3 — Patient Journey Timeline                           │
// │ PRG-006 — Migrate from in-memory to D1 persistence          │
// └─────────────────────────────────────────────────────────────┘

import {
  IvfStage,
  DEFAULT_STAGE_DURATIONS,
  STAGE_LABELS,
  STAGE_TRANSITIONS,
  STAGE_MILESTONE_TEMPLATES,
} from "./timeline-types.js";

import type {
  TimelineEngine,
  StageStatus,
  StageStatusValue,
  Milestone,
  MilestoneType,
  TimelineEvent,
  EventCategory,
  ProgressSummary,
  ExpectedDateInfo,
  FullTimeline,
} from "./timeline-types.js";

// ── Ordered stage list (matches enum declaration order) ───────

const STAGE_ORDER: IvfStage[] = [
  IvfStage.registration,
  IvfStage.consultation,
  IvfStage.treatment_plan,
  IvfStage.ivf_cycle,
  IvfStage.retrieval,
  IvfStage.transfer,
  IvfStage.follow_up,
  IvfStage.success,
];

// ── DB row shapes ─────────────────────────────────────────────

interface StageRow {
  id: string;
  identity_id: string;
  stage: string;
  status: string;
  entered_at: string | null;
  completed_at: string | null;
  expected_duration_days: number;
  expected_completion_date: string | null;
  actual_duration_days: number | null;
  notes: string;
  created_at: string;
  updated_at: string;
}

interface MilestoneRow {
  id: string;
  identity_id: string;
  type: string;
  title: string;
  description: string;
  stage: string | null;
  date: string;
  achieved: number;
  achieved_at: string | null;
  expected_date: string | null;
  auto_generated: number;
  created_at: string;
  updated_at: string;
}

interface EventRow {
  id: string;
  identity_id: string;
  category: string;
  title: string;
  description: string;
  ref_id: string | null;
  ref_type: string | null;
  occurred_at: string;
  created_at: string;
}

// ── Utilities ─────────────────────────────────────────────────

function nowIso(): string {
  return new Date().toISOString();
}

function addDays(isoDate: string, days: number): string {
  const d = new Date(isoDate);
  d.setUTCDate(d.getUTCDate() + days);
  return d.toISOString();
}

function daysBetween(start: string, end: string): number {
  const ms = new Date(end).getTime() - new Date(start).getTime();
  return Math.round(ms / 86_400_000);
}

function newId(): string {
  // crypto.randomUUID is available in CF Workers and Node ≥ 19
  return crypto.randomUUID();
}

// ── Row → domain mappers ──────────────────────────────────────

function rowToStageStatus(row: StageRow): StageStatus {
  return {
    stage: row.stage as IvfStage,
    label: STAGE_LABELS[row.stage as IvfStage],
    status: row.status as StageStatusValue,
    enteredAt: row.entered_at,
    completedAt: row.completed_at,
    expectedDurationDays: row.expected_duration_days,
    expectedCompletionDate: row.expected_completion_date,
    actualDurationDays: row.actual_duration_days,
    notes: row.notes,
  };
}

function rowToMilestone(row: MilestoneRow): Milestone {
  return {
    id: row.id,
    type: row.type as MilestoneType,
    title: row.title,
    description: row.description,
    stage: row.stage as IvfStage,
    date: row.date,
    achieved: row.achieved === 1,
    achievedAt: row.achieved_at,
    expectedDate: row.expected_date,
    autoGenerated: row.auto_generated === 1,
  };
}

function rowToEvent(row: EventRow): TimelineEvent {
  return {
    id: row.id,
    timestamp: row.occurred_at,
    category: row.category as EventCategory,
    title: row.title,
    description: row.description,
    refId: row.ref_id,
    refType: row.ref_type as "stage" | "milestone" | null,
  };
}

// ── D1TimelineEngine ──────────────────────────────────────────

export class D1TimelineEngine implements TimelineEngine {
  constructor(private db: D1Database) {}

  // ── First-access initialization ─────────────────────────────

  private async ensureInitialized(identityId: string): Promise<void> {
    const countResult = await this.db
      .prepare("SELECT COUNT(*) AS cnt FROM patient_stages WHERE identity_id = ?")
      .bind(identityId)
      .first<{ cnt: number }>();

    if (countResult && countResult.cnt > 0) {
      // Self-heal legacy rows: a journey with zero active stages but some
      // pending stages is an invalid state (would falsely show "completed").
      // Promote the first pending stage to active so there is a real current
      // stage. (Registration may legitimately be the only stage for a freshly
      // reset account — in that case leave it; the page handles that.)
      await this.healActiveStage(identityId);
      return; // already seeded
    }

    const now = nowIso();
    const stmts: D1PreparedStatement[] = [];

    // Insert all 8 stages. Registration is completed on creation; the next
    // stage (consultation) is the active stage so a new patient has a real
    // "current stage" instead of a false "journey completed" state.
    for (const stage of STAGE_ORDER) {
      const isRegistration = stage === IvfStage.registration;
      const isFirstActive = stage === STAGE_ORDER[1]; // consultation
      const status: StageStatusValue = isRegistration
        ? "completed"
        : isFirstActive
          ? "active"
          : "pending";
      const enteredAt = isRegistration || isFirstActive ? now : null;
      const completedAt = isRegistration ? now : null;
      const expectedDurationDays = DEFAULT_STAGE_DURATIONS[stage];
      const expectedCompletionDate = isRegistration || isFirstActive
        ? addDays(now, expectedDurationDays)
        : null;
      const actualDurationDays = isRegistration ? 0 : null;

      stmts.push(
        this.db
          .prepare(
            `INSERT INTO patient_stages
               (id, identity_id, stage, status, entered_at, completed_at,
                expected_duration_days, expected_completion_date,
                actual_duration_days, notes, created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, '', ?, ?)`,
          )
          .bind(
            newId(),
            identityId,
            stage,
            status,
            enteredAt,
            completedAt,
            expectedDurationDays,
            expectedCompletionDate,
            actualDurationDays,
            now,
            now,
          ),
      );
    }

    // Insert the initial registration milestone (already achieved)
    const regTemplates = STAGE_MILESTONE_TEMPLATES[IvfStage.registration];
    if (regTemplates.length > 0) {
      const tpl = regTemplates[0];
      stmts.push(
        this.db
          .prepare(
            `INSERT INTO patient_milestones
               (id, identity_id, type, title, description, stage, date,
                achieved, achieved_at, expected_date, auto_generated,
                created_at, updated_at)
             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          )
          .bind(
            newId(),
            identityId,
            tpl.type,
            tpl.title,
            tpl.description,
            IvfStage.registration,
            now,
            1,
            now,
            now,
            1,
            now,
            now,
          ),
      );
    }

    // Insert the initial system event
    stmts.push(
      this.db
        .prepare(
          `INSERT INTO patient_timeline_events
             (id, identity_id, category, title, description,
              ref_id, ref_type, occurred_at, created_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        )
        .bind(
          newId(),
          identityId,
          "stage_change",
          "Registration Completed",
          "Patient profile created and registration stage completed.",
          IvfStage.registration,
          "stage",
          now,
          now,
        ),
    );

    await this.db.batch(stmts);
  }

  /**
   * Self-heal: if a journey has no active stage but has pending stages,
   * promote the earliest pending stage to active. This corrects the legacy
   * seed where every new patient had registration=completed and all others
   * =pending (no active), which made the UI falsely report "journey completed".
   * If there are zero pending stages (e.g. a genuinely finished journey, or a
   * freshly-reset account with only registration), this is a no-op.
   */
  private async healActiveStage(identityId: string): Promise<void> {
    const { results } = await this.db
      .prepare(
        "SELECT * FROM patient_stages WHERE identity_id = ? ORDER BY rowid ASC",
      )
      .bind(identityId)
      .all<StageRow>();

    const hasActive = results.some((r) => r.status === "active");
    if (hasActive) return;

    const pending = results.find((r) => r.status === "pending");
    if (!pending) return; // nothing to promote

    const now = nowIso();
    await this.db
      .prepare(
        `UPDATE patient_stages
           SET status = 'active', entered_at = ?, updated_at = ?
           WHERE id = ?`,
      )
      .bind(now, now, pending.id)
      .run();
  }

  // ── getStages ────────────────────────────────────────────────

  async getStages(identityId: string): Promise<StageStatus[]> {
    await this.ensureInitialized(identityId);
    const { results } = await this.db
      .prepare(
        "SELECT * FROM patient_stages WHERE identity_id = ? ORDER BY rowid ASC",
      )
      .bind(identityId)
      .all<StageRow>();

    // Return in canonical stage order
    const byStage = new Map(results.map((r) => [r.stage, r]));
    return STAGE_ORDER.map((s) => rowToStageStatus(byStage.get(s)!)).filter(Boolean);
  }

  // ── getStage ─────────────────────────────────────────────────

  async getStage(identityId: string, stage: IvfStage): Promise<StageStatus | null> {
    await this.ensureInitialized(identityId);
    const row = await this.db
      .prepare(
        "SELECT * FROM patient_stages WHERE identity_id = ? AND stage = ?",
      )
      .bind(identityId, stage)
      .first<StageRow>();
    return row ? rowToStageStatus(row) : null;
  }

  // ── advanceStage ─────────────────────────────────────────────

  async advanceStage(identityId: string, notes: string): Promise<StageStatus> {
    await this.ensureInitialized(identityId);
    const now = nowIso();

    // Fetch all stages in order
    const stages = await this.getStages(identityId);

    // Find the currently active stage
    let activeStage = stages.find((s) => s.status === "active");

    // If no active stage, find the first pending stage after the last completed
    if (!activeStage) {
      const lastCompleted = [...stages].reverse().find((s) => s.status === "completed");
      if (lastCompleted) {
        const lastIdx = STAGE_ORDER.indexOf(lastCompleted.stage);
        activeStage = stages.find(
          (s) => STAGE_ORDER.indexOf(s.stage) > lastIdx && s.status === "pending",
        );
      } else {
        activeStage = stages.find((s) => s.status === "pending");
      }
    }

    if (!activeStage) {
      throw new Error("No stage available to advance — all stages may be complete.");
    }

    const activeIdx = STAGE_ORDER.indexOf(activeStage.stage);
    const nextStage =
      STAGE_TRANSITIONS[activeStage.stage]?.[0] ?? null;

    const actualDuration = activeStage.enteredAt
      ? daysBetween(activeStage.enteredAt, now)
      : 0;

    const stmts: D1PreparedStatement[] = [];

    // Complete the current stage
    stmts.push(
      this.db
        .prepare(
          `UPDATE patient_stages
             SET status = 'completed', completed_at = ?, actual_duration_days = ?,
                 notes = ?, updated_at = ?
           WHERE identity_id = ? AND stage = ?`,
        )
        .bind(now, actualDuration, notes, now, identityId, activeStage.stage),
    );

    // Activate the next stage
    if (nextStage) {
      const nextDuration = DEFAULT_STAGE_DURATIONS[nextStage];
      const expectedCompletion = addDays(now, nextDuration);
      stmts.push(
        this.db
          .prepare(
            `UPDATE patient_stages
               SET status = 'active', entered_at = ?,
                   expected_completion_date = ?, updated_at = ?
             WHERE identity_id = ? AND stage = ?`,
          )
          .bind(now, expectedCompletion, now, identityId, nextStage),
      );
    }

    // Write stage_change event for the completed stage
    stmts.push(
      this.db
        .prepare(
          `INSERT INTO patient_timeline_events
             (id, identity_id, category, title, description,
              ref_id, ref_type, occurred_at, created_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        )
        .bind(
          newId(),
          identityId,
          "stage_change",
          `${STAGE_LABELS[activeStage.stage]} Completed`,
          notes || `${STAGE_LABELS[activeStage.stage]} stage completed.`,
          activeStage.stage,
          "stage",
          now,
          now,
        ),
    );

    // Auto-generate milestones for the newly activated stage
    if (nextStage) {
      const templates = STAGE_MILESTONE_TEMPLATES[nextStage] ?? [];
      for (const tpl of templates) {
        stmts.push(
          this.db
            .prepare(
              `INSERT INTO patient_milestones
                 (id, identity_id, type, title, description, stage, date,
                  achieved, achieved_at, expected_date, auto_generated,
                  created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
            )
            .bind(
              newId(),
              identityId,
              tpl.type,
              tpl.title,
              tpl.description,
              nextStage,
              now,
              0,
              null,
              addDays(now, DEFAULT_STAGE_DURATIONS[nextStage]),
              1,
              now,
              now,
            ),
        );
      }
    }

    await this.db.batch(stmts);

    // Return the stage that was just completed
    const updated = await this.db
      .prepare(
        "SELECT * FROM patient_stages WHERE identity_id = ? AND stage = ?",
      )
      .bind(identityId, activeStage.stage)
      .first<StageRow>();

    if (!updated) {
      throw new Error("Failed to retrieve updated stage after advance.");
    }

    return rowToStageStatus(updated);
  }

  // ── getMilestones ────────────────────────────────────────────

  async getMilestones(identityId: string): Promise<Milestone[]> {
    await this.ensureInitialized(identityId);
    const { results } = await this.db
      .prepare(
        "SELECT * FROM patient_milestones WHERE identity_id = ? ORDER BY date ASC",
      )
      .bind(identityId)
      .all<MilestoneRow>();
    return results.map(rowToMilestone);
  }

  // ── getMilestone ─────────────────────────────────────────────

  async getMilestone(identityId: string, id: string): Promise<Milestone | null> {
    await this.ensureInitialized(identityId);
    const row = await this.db
      .prepare(
        "SELECT * FROM patient_milestones WHERE identity_id = ? AND id = ?",
      )
      .bind(identityId, id)
      .first<MilestoneRow>();
    return row ? rowToMilestone(row) : null;
  }

  // ── achieveMilestone ─────────────────────────────────────────

  async achieveMilestone(identityId: string, id: string): Promise<Milestone> {
    await this.ensureInitialized(identityId);
    const now = nowIso();

    const existing = await this.getMilestone(identityId, id);
    if (!existing) {
      throw new Error(`Milestone not found: ${id}`);
    }
    if (existing.achieved) {
      throw new Error(`Milestone already achieved: ${id}`);
    }

    await this.db
      .prepare(
        `UPDATE patient_milestones
           SET achieved = 1, achieved_at = ?, updated_at = ?
         WHERE identity_id = ? AND id = ?`,
      )
      .bind(now, now, identityId, id)
      .run();

    // Write milestone_achieved event
    await this.db
      .prepare(
        `INSERT INTO patient_timeline_events
           (id, identity_id, category, title, description,
            ref_id, ref_type, occurred_at, created_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      )
      .bind(
        newId(),
        identityId,
        "milestone_achieved",
        existing.title,
        existing.description,
        id,
        "milestone",
        now,
        now,
      )
      .run();

    const updated = await this.db
      .prepare(
        "SELECT * FROM patient_milestones WHERE identity_id = ? AND id = ?",
      )
      .bind(identityId, id)
      .first<MilestoneRow>();

    if (!updated) {
      throw new Error("Failed to retrieve milestone after achieving.");
    }

    return rowToMilestone(updated);
  }

  // ── getEvents ────────────────────────────────────────────────

  async getEvents(identityId: string): Promise<TimelineEvent[]> {
    await this.ensureInitialized(identityId);
    const { results } = await this.db
      .prepare(
        `SELECT * FROM patient_timeline_events
          WHERE identity_id = ?
          ORDER BY occurred_at ASC`,
      )
      .bind(identityId)
      .all<EventRow>();
    return results.map(rowToEvent);
  }

  // ── getProgress ──────────────────────────────────────────────

  async getProgress(identityId: string): Promise<ProgressSummary> {
    await this.ensureInitialized(identityId);

    const stages = await this.getStages(identityId);
    const milestones = await this.getMilestones(identityId);

    const stagesTotal = stages.length;
    const stagesCompleted = stages.filter((s) => s.status === "completed").length;
    const overallPercent =
      stagesTotal > 0 ? Math.round((stagesCompleted / stagesTotal) * 100) : 0;

    const currentStageStatus = stages.find((s) => s.status === "active");
    const currentStage = currentStageStatus?.stage ?? null;

    const milestonesTotal = milestones.length;
    const milestonesAchieved = milestones.filter((m) => m.achieved).length;

    // Estimate remaining days: sum durations of pending/active stages
    const pendingAndActive = stages.filter(
      (s) => s.status === "active" || s.status === "pending",
    );
    const estimatedRemainingDays =
      pendingAndActive.length > 0
        ? pendingAndActive.reduce((sum, s) => sum + s.expectedDurationDays, 0)
        : null;

    return {
      overallPercent,
      stagesCompleted,
      stagesTotal,
      currentStage,
      milestonesAchieved,
      milestonesTotal,
      estimatedRemainingDays,
    };
  }

  // ── getExpectedDates ─────────────────────────────────────────

  async getExpectedDates(identityId: string): Promise<ExpectedDateInfo[]> {
    await this.ensureInitialized(identityId);

    const stages = await this.getStages(identityId);

    // Build a running cursor for future stages starting from now
    const now = nowIso();
    let cursor: string = now;

    // Find the anchor: the enteredAt of the earliest non-completed stage,
    // or fall back to the completedAt of the last completed stage, or now.
    const firstActive = stages.find((s) => s.status === "active");
    const firstPending = stages.find((s) => s.status === "pending");

    if (firstActive?.enteredAt) {
      cursor = firstActive.enteredAt;
    } else if (firstPending) {
      const lastCompleted = [...stages].reverse().find((s) => s.status === "completed");
      cursor = lastCompleted?.completedAt ?? now;
    }

    return stages.map((s) => {
      let estimatedStartDate: string | null = null;
      let estimatedCompletionDate: string | null = null;

      if (s.status === "completed") {
        estimatedStartDate = s.enteredAt;
        estimatedCompletionDate = s.completedAt;
      } else if (s.status === "active") {
        estimatedStartDate = s.enteredAt ?? cursor;
        estimatedCompletionDate =
          s.expectedCompletionDate ?? addDays(cursor, s.expectedDurationDays);
        // Advance cursor past this stage
        cursor = estimatedCompletionDate;
      } else {
        // pending
        estimatedStartDate = cursor;
        estimatedCompletionDate = addDays(cursor, s.expectedDurationDays);
        cursor = estimatedCompletionDate;
      }

      return {
        stage: s.stage,
        label: s.label,
        estimatedStartDate,
        estimatedCompletionDate,
      };
    });
  }

  // ── getTimeline ──────────────────────────────────────────────

  async getTimeline(identityId: string): Promise<FullTimeline> {
    // ensureInitialized is called by each sub-method; call once here explicitly
    await this.ensureInitialized(identityId);

    const [stages, milestones, events, progress, expectedDates] = await Promise.all([
      this.getStages(identityId),
      this.getMilestones(identityId),
      this.getEvents(identityId),
      this.getProgress(identityId),
      this.getExpectedDates(identityId),
    ]);

    return { stages, milestones, events, progress, expectedDates };
  }
}
