// ┌─────────────────────────────────────────────────────────────┐
// │ Timeline Engine — InMemory Implementation                     │
// │ Wave 3 — Patient Journey Timeline                            │
// └─────────────────────────────────────────────────────────────┘

import {
  type TimelineEngine,
  type IvfStage,
  type StageStatus,
  type Milestone,
  type TimelineEvent,
  type ProgressSummary,
  type ExpectedDateInfo,
  type FullTimeline,
  type MilestoneTemplate,
  DEFAULT_STAGE_DURATIONS,
  STAGE_LABELS,
  STAGE_TRANSITIONS,
  STAGE_MILESTONE_TEMPLATES,
} from "./timeline-types.js";

function now(): string {
  return new Date().toISOString();
}

function generateId(): string {
  return crypto.randomUUID();
}

function createPatientZeroStages(): StageStatus[] {
  const stages: StageStatus[] = [];
  const stageOrder: IvfStage[] = [
    IvfStage.registration,
    IvfStage.consultation,
    IvfStage.treatment_plan,
    IvfStage.ivf_cycle,
    IvfStage.retrieval,
    IvfStage.transfer,
    IvfStage.follow_up,
    IvfStage.success,
  ];

  for (const stage of stageOrder) {
    stages.push({
      stage,
      label: STAGE_LABELS[stage],
      status: stage === IvfStage.registration ? "completed" : "pending",
      enteredAt: stage === IvfStage.registration ? now() : null,
      completedAt: stage === IvfStage.registration ? now() : null,
      expectedDurationDays: DEFAULT_STAGE_DURATIONS[stage],
      expectedCompletionDate: null,
      actualDurationDays: stage === IvfStage.registration ? 0 : null,
      notes: "",
    });
  }

  return stages;
}

function createPatientZeroMilestones(): Milestone[] {
  return [
    {
      id: generateId(),
      type: "registration",
      title: "Account Created",
      description: "Welcome to AG Synergy. Your fertility journey has not yet begun. Your next step is completing your profile and requesting your first consultation.",
      date: now(),
      achieved: true,
      achievedAt: now(),
      expectedDate: null,
      autoGenerated: true,
    },
  ];
}

export class InMemoryTimelineEngine implements TimelineEngine {
  private stores: Map<string, { stages: StageStatus[]; milestones: Milestone[]; events: TimelineEvent[] }> = new Map();

  private getOrCreateStore(identityId: string) {
    if (!this.stores.has(identityId)) {
      this.stores.set(identityId, {
        stages: createPatientZeroStages(),
        milestones: createPatientZeroMilestones(),
        events: [],
      });
    }
    return this.stores.get(identityId)!;
  }

  private getStageIndex(stages: StageStatus[], stage: IvfStage): number {
    return stages.findIndex((s) => s.stage === stage);
  }

  private recalcExpectedDates(stages: StageStatus[]): ExpectedDateInfo[] {
    const result: ExpectedDateInfo[] = [];
    const nowDate = new Date();

    for (let i = 0; i < stages.length; i++) {
      const s = stages[i];
      let estimatedStart: string | null = null;
      let estimatedCompletion: string | null = null;

      if (s.status === "completed" && s.enteredAt && s.completedAt) {
        estimatedStart = s.enteredAt;
        estimatedCompletion = s.completedAt;
      } else if (s.status === "active" && s.enteredAt) {
        estimatedStart = s.enteredAt;
        const dur = s.expectedDurationDays;
        if (dur > 0) {
          const comp = new Date(s.enteredAt);
          comp.setDate(comp.getDate() + dur);
          estimatedCompletion = comp.toISOString();
        }
      } else if (s.status === "pending") {
        // Find the most recent completed or active predecessor
        let predecessorDate: Date | null = null;
        for (let j = i - 1; j >= 0; j--) {
          if (stages[j].status === "completed" && stages[j].completedAt) {
            predecessorDate = new Date(stages[j].completedAt);
            break;
          }
          if (stages[j].status === "active" && stages[j].enteredAt) {
            predecessorDate = new Date(stages[j].enteredAt);
            break;
          }
        }

        if (predecessorDate) {
          // Estimate start: predecessor completion + 1 day gap
          const startDate = new Date(predecessorDate);
          startDate.setDate(startDate.getDate() + 1);
          estimatedStart = startDate.toISOString();

          // Estimate completion: start + duration
          const dur = DEFAULT_STAGE_DURATIONS[s.stage];
          if (dur > 0) {
            const compDate = new Date(startDate);
            compDate.setDate(compDate.getDate() + dur);
            estimatedCompletion = compDate.toISOString();
          }
        } else {
          // Far future: estimate from now + (index * 30 days)
          const startDate = new Date(nowDate);
          startDate.setDate(startDate.getDate() + i * 30);
          estimatedStart = startDate.toISOString();

          const dur = DEFAULT_STAGE_DURATIONS[s.stage];
          if (dur > 0) {
            const compDate = new Date(startDate);
            compDate.setDate(compDate.getDate() + dur);
            estimatedCompletion = compDate.toISOString();
          }
        }
      }

      result.push({
        stage: s.stage,
        label: s.label,
        estimatedStartDate: estimatedStart,
        estimatedCompletionDate: estimatedCompletion,
      });
    }

    return result;
  }

  async getTimeline(identityId: string): Promise<FullTimeline> {
    const store = this.getOrCreateStore(identityId);
    const stages = store.stages;
    const milestones = store.milestones;
    const events = store.events;
    const progress = this.calcProgress(stages, milestones);
    const expectedDates = this.recalcExpectedDates(stages);

    return { stages, milestones, events, progress, expectedDates };
  }

  async getStages(identityId: string): Promise<StageStatus[]> {
    const store = this.getOrCreateStore(identityId);
    return store.stages;
  }

  async getStage(identityId: string, stage: IvfStage): Promise<StageStatus | null> {
    const store = this.getOrCreateStore(identityId);
    return store.stages.find((s) => s.stage === stage) ?? null;
  }

  async advanceStage(identityId: string, notes: string): Promise<StageStatus> {
    const store = this.getOrCreateStore(identityId);
    const stages = store.stages;

    // Find the active stage
    const activeIndex = stages.findIndex((s) => s.status === "active");
    if (activeIndex === -1) {
      // No active stage — find the first pending stage after the last completed
      const lastCompletedIndex = stages.reduce(
        (max, s, i) => (s.status === "completed" ? i : max),
        -1,
      );
      const nextIndex = lastCompletedIndex + 1;
      if (nextIndex >= stages.length) {
        throw new Error("No stages remaining to advance to");
      }
      // Activate the next stage
      stages[nextIndex].status = "active";
      stages[nextIndex].enteredAt = now();
      stages[nextIndex].expectedCompletionDate = this.calcExpectedCompletion(stages[nextIndex]);

      // Add stage_change event
      store.events.unshift({
        id: generateId(),
        timestamp: now(),
        category: "stage_change",
        title: `Stage started: ${STAGE_LABELS[stages[nextIndex].stage]}`,
        description: `Patient has entered the ${STAGE_LABELS[stages[nextIndex].stage]} stage.`,
        refId: stages[nextIndex].stage,
        refType: "stage",
      });

      // Auto-generate milestones for this stage
      this.autoGenerateMilestones(stages[nextIndex].stage, store);

      // Save notes on the stage being activated (first stage has no notes)
      if (notes && stages[nextIndex].stage === IvfStage.registration) {
        // Registration stage notes
      }

      return stages[nextIndex];
    }

    // Complete the active stage
    const activeStage = stages[activeIndex];
    activeStage.status = "completed";
    activeStage.completedAt = now();
    if (activeStage.enteredAt) {
      const entered = new Date(activeStage.enteredAt);
      const completed = new Date(activeStage.completedAt!);
      activeStage.actualDurationDays = Math.floor(
        (completed.getTime() - entered.getTime()) / 86_400_000,
      );
    }
    activeStage.notes = notes;

    // Add milestone_achieved event for auto-generated milestones of this stage
    for (const m of store.milestones) {
      if (m.stage === activeStage.stage && m.autoGenerated && !m.achieved) {
        m.achieved = true;
        m.achievedAt = now();
        store.events.unshift({
          id: generateId(),
          timestamp: now(),
          category: "milestone_achieved",
          title: `Milestone achieved: ${m.title}`,
          description: m.description,
          refId: m.id,
          refType: "milestone",
        });
      }
    }

    // Add stage_change event for completion
    store.events.unshift({
      id: generateId(),
      timestamp: now(),
      category: "stage_change",
      title: `Stage completed: ${activeStage.label}`,
      description: notes || `Stage ${activeStage.label} completed.`,
      refId: activeStage.stage,
      refType: "stage",
    });

    // Advance to next stage
    const transitions = STAGE_TRANSITIONS[activeStage.stage];
    if (transitions.length === 0) {
      // Terminal stage (success) — no further advancement
      return activeStage;
    }

    const nextStage = transitions[0];
    const nextIndex = this.getStageIndex(stages, nextStage);
    if (nextIndex !== -1) {
      stages[nextIndex].status = "active";
      stages[nextIndex].enteredAt = now();
      stages[nextIndex].expectedCompletionDate = this.calcExpectedCompletion(stages[nextIndex]);

      // Add stage_change event for the new active stage
      store.events.unshift({
        id: generateId(),
        timestamp: now(),
        category: "stage_change",
        title: `Stage started: ${STAGE_LABELS[stages[nextIndex].stage]}`,
        description: `Patient has entered the ${STAGE_LABELS[stages[nextIndex].stage]} stage.`,
        refId: stages[nextIndex].stage,
        refType: "stage",
      });

      // Auto-generate milestones for the new active stage
      this.autoGenerateMilestones(stages[nextIndex].stage, store);
    }

    return activeStage;
  }

  private calcExpectedCompletion(stage: StageStatus): string | null {
    if (!stage.enteredAt || stage.expectedDurationDays <= 0) return null;
    const d = new Date(stage.enteredAt);
    d.setDate(d.getDate() + stage.expectedDurationDays);
    return d.toISOString();
  }

  private autoGenerateMilestones(stage: IvfStage, store: { stages: StageStatus[]; milestones: Milestone[]; events: TimelineEvent[] }): void {
    const templates = STAGE_MILESTONE_TEMPLATES[stage] || [];
    for (const tpl of templates) {
      const exists = store.milestones.some((m) => m.type === tpl.type);
      if (!exists) {
        store.milestones.push({
          id: generateId(),
          type: tpl.type,
          title: tpl.title,
          description: tpl.description,
          stage,
          date: now(),
          achieved: false,
          achievedAt: null,
          expectedDate: null,
          autoGenerated: true,
        });
      }
    }
  }

  async getMilestones(identityId: string): Promise<Milestone[]> {
    const store = this.getOrCreateStore(identityId);
    return store.milestones;
  }

  async getMilestone(identityId: string, id: string): Promise<Milestone | null> {
    const store = this.getOrCreateStore(identityId);
    return store.milestones.find((m) => m.id === id) ?? null;
  }

  async achieveMilestone(identityId: string, id: string): Promise<Milestone> {
    const store = this.getOrCreateStore(identityId);
    const milestone = store.milestones.find((m) => m.id === id);
    if (!milestone) {
      throw new Error(`Milestone not found: ${id}`);
    }
    if (milestone.achieved) {
      return milestone;
    }
    milestone.achieved = true;
    milestone.achievedAt = now();

    store.events.unshift({
      id: generateId(),
      timestamp: now(),
      category: "milestone_achieved",
      title: `Milestone achieved: ${milestone.title}`,
      description: milestone.description,
      refId: milestone.id,
      refType: "milestone",
    });

    return milestone;
  }

  async getEvents(identityId: string): Promise<TimelineEvent[]> {
    const store = this.getOrCreateStore(identityId);
    return store.events;
  }

  async getProgress(identityId: string): Promise<ProgressSummary> {
    const store = this.getOrCreateStore(identityId);
    return this.calcProgress(store.stages, store.milestones);
  }

  private calcProgress(stages: StageStatus[], milestones: Milestone[]): ProgressSummary {
    const totalStages = stages.length;
    const completedStages = stages.filter((s) => s.status === "completed").length;
    const overallPercent = totalStages > 0 ? Math.round((completedStages / totalStages) * 100) : 0;

    const currentStage = stages.find((s) => s.status === "active") ?? null;
    const milestonesAchieved = milestones.filter((m) => m.achieved).length;
    const milestonesTotal = milestones.length;

    // Remaining days: sum durations for stages after the current active stage
    let remainingDays = 0;
    if (currentStage) {
      const currentIdx = this.getStageIndex(stages, currentStage.stage);
      for (let i = currentIdx + 1; i < stages.length; i++) {
        remainingDays += DEFAULT_STAGE_DURATIONS[stages[i].stage];
      }
    }

    return {
      overallPercent,
      stagesCompleted: completedStages,
      stagesTotal: totalStages,
      currentStage: currentStage?.stage ?? null,
      milestonesAchieved,
      milestonesTotal,
      estimatedRemainingDays: remainingDays > 0 ? remainingDays : null,
    };
  }

  async getExpectedDates(identityId: string): Promise<ExpectedDateInfo[]> {
    const store = this.getOrCreateStore(identityId);
    return this.recalcExpectedDates(store.stages);
  }
}
