// ┌─────────────────────────────────────────────────────────────┐
// │ AI Platform — Timeline Types                               │
// │ IVF journey stages, milestones, events, and progress data. │
// │ Wave 3 — Timeline Engine                                    │
// └─────────────────────────────────────────────────────────────┘
//
// PHI Boundary: This capability stores timeline metadata only.
// No PHI payloads — patient references are opaque identity IDs.

// ════════════════════════════════════════════════════════════
// IVF Stage Progression
// ════════════════════════════════════════════════════════════

/** Ordered list of all IVF journey stages */
export const IVF_STAGES = [
  "registration",
  "consultation",
  "treatment_plan",
  "ivf_cycle",
  "retrieval",
  "transfer",
  "follow_up",
  "success",
] as const;

export type IvfStage = (typeof IVF_STAGES)[number];

/** Human-readable labels for each stage */
export const IVF_STAGE_LABELS: Record<IvfStage, string> = {
  registration: "Registration",
  consultation: "Consultation",
  treatment_plan: "Treatment Plan",
  ivf_cycle: "IVF Cycle",
  retrieval: "Retrieval",
  transfer: "Transfer",
  follow_up: "Follow-up",
  success: "Success",
};

/** Stage progression engine — valid forward transitions only */
export const STAGE_TRANSITIONS: Record<IvfStage, IvfStage[]> = {
  registration: ["consultation"],
  consultation: ["treatment_plan"],
  treatment_plan: ["ivf_cycle"],
  ivf_cycle: ["retrieval"],
  retrieval: ["transfer"],
  transfer: ["follow_up"],
  follow_up: ["success"],
  success: [], // terminal
};

// ════════════════════════════════════════════════════════════
// Stage Status
// ════════════════════════════════════════════════════════════

export interface StageStatus {
  stage: IvfStage;
  label: string;
  status: "pending" | "active" | "completed" | "skipped";
  enteredAt: string | null;
  completedAt: string | null;
  expectedDurationDays: number;
  /** Estimated date this stage will complete (null until stage is active) */
  expectedCompletionDate: string | null;
  /** Actual duration in days (null if still active or pending) */
  actualDurationDays: number | null;
  /** Notes from provider */
  notes: string;
}

// ════════════════════════════════════════════════════════════
// Milestones
// ════════════════════════════════════════════════════════════

export const MILESTONE_TYPES = [
  "registration",
  "consultation",
  "treatment_plan",
  "ivf_cycle_start",
  "retrieval",
  "transfer",
  "pregnancy_test",
  "follow_up",
  "success",
  "procedure",
  "custom",
] as const;

export type MilestoneType = (typeof MILESTONE_TYPES)[number];

export interface Milestone {
  id: string;
  type: MilestoneType;
  title: string;
  description: string;
  stage: IvfStage;
  date: string;
  achieved: boolean;
  achievedAt: string | null;
  /** Expected date (auto-generated, can be overridden) */
  expectedDate: string | null;
  /** Auto-generated vs manually created */
  autoGenerated: boolean;
}

// ════════════════════════════════════════════════════════════
// Historical Events
// ════════════════════════════════════════════════════════════

export const EVENT_CATEGORIES = [
  "stage_change",
  "milestone_achieved",
  "task_completed",
  "appointment_scheduled",
  "note_added",
  "system",
] as const;

export type EventCategory = (typeof EVENT_CATEGORIES)[number];

export interface TimelineEvent {
  id: string;
  timestamp: string;
  category: EventCategory;
  title: string;
  description: string;
  /** Reference to related entity (milestone id, stage name, etc.) */
  refId: string | null;
  refType: string | null;
}

// ════════════════════════════════════════════════════════════
// Progress Tracking
// ════════════════════════════════════════════════════════════

export interface ProgressSummary {
  /** Overall completion percentage (0–100) */
  overallPercent: number;
  /** Stages completed */
  stagesCompleted: number;
  /** Total stages */
  stagesTotal: number;
  /** Current stage label */
  currentStage: string | null;
  /** Milestones achieved */
  milestonesAchieved: number;
  /** Total milestones */
  milestonesTotal: number;
  /** Estimated remaining time in days */
  estimatedRemainingDays: number | null;
}

// ════════════════════════════════════════════════════════════
// Expected Date Calculations
// ════════════════════════════════════════════════════════════

export interface ExpectedDateInfo {
  stage: IvfStage;
  label: string;
  /** Estimated date this stage will begin */
  estimatedStartDate: string | null;
  /** Estimated date this stage will complete */
  estimatedCompletionDate: string | null;
  /** Typical duration of this stage in days */
  typicalDurationDays: number;
  /** Whether this estimate is based on actual data or defaults */
  estimateType: "default" | "adjusted";
}

// ════════════════════════════════════════════════════════════
// Full Timeline Data
// ════════════════════════════════════════════════════════════

export interface TimelineData {
  patientId: string;
  stages: StageStatus[];
  milestones: Milestone[];
  events: TimelineEvent[];
  progress: ProgressSummary;
  expectedDates: ExpectedDateInfo[];
  updatedAt: string;
  createdAt: string;
}