// ┌─────────────────────────────────────────────────────────────┐
// │ Timeline Engine — Domain Types                                │
// │ Wave 3 — Patient Journey Timeline                            │
// └─────────────────────────────────────────────────────────────┘

// ── Ordered Stage Enum ──────────────────────────────────────
// Order defines progression. Do not reorder.

export enum IvfStage {
  registration = "registration",
  consultation = "consultation",
  treatment_plan = "treatment_plan",
  ivf_cycle = "ivf_cycle",
  retrieval = "retrieval",
  transfer = "transfer",
  follow_up = "follow_up",
  success = "success",
}

// ── Stage Status ─────────────────────────────────────────────

export type StageStatusValue = "pending" | "active" | "completed" | "skipped";

export interface StageStatus {
  stage: IvfStage;
  label: string;
  status: StageStatusValue;
  enteredAt: string | null;
  completedAt: string | null;
  expectedDurationDays: number;
  expectedCompletionDate: string | null;
  actualDurationDays: number | null;
  notes: string;
}

// ── Milestone ────────────────────────────────────────────────

export type MilestoneType =
  | "registration"
  | "consultation"
  | "treatment_plan"
  | "ivf_cycle_start"
  | "retrieval"
  | "transfer"
  | "pregnancy_test"
  | "follow_up"
  | "success"
  | "custom";

export interface Milestone {
  id: string;
  type: MilestoneType;
  title: string;
  description: string;
  stage: IvfStage;
  date: string;
  achieved: boolean;
  achievedAt: string | null;
  expectedDate: string | null;
  autoGenerated: boolean;
}

// ── Timeline Event ───────────────────────────────────────────

export type EventCategory =
  | "stage_change"
  | "milestone_achieved"
  | "task_completed"
  | "appointment_scheduled"
  | "note_added"
  | "system";

export interface TimelineEvent {
  id: string;
  timestamp: string;
  category: EventCategory;
  title: string;
  description: string;
  refId: string | null;
  refType: "stage" | "milestone" | null;
}

// ── Progress Summary ─────────────────────────────────────────

export interface ProgressSummary {
  overallPercent: number;
  stagesCompleted: number;
  stagesTotal: number;
  currentStage: IvfStage | null;
  milestonesAchieved: number;
  milestonesTotal: number;
  estimatedRemainingDays: number | null;
}

// ── Expected Date Info ───────────────────────────────────────

export interface ExpectedDateInfo {
  stage: IvfStage;
  label: string;
  estimatedStartDate: string | null;
  estimatedCompletionDate: string | null;
}

// ── Full Timeline ────────────────────────────────────────────

export interface FullTimeline {
  stages: StageStatus[];
  milestones: Milestone[];
  events: TimelineEvent[];
  progress: ProgressSummary;
  expectedDates: ExpectedDateInfo[];
}

// ── Stage Transition ─────────────────────────────────────────

export interface StageTransition {
  from: IvfStage;
  to: IvfStage;
  allowed: boolean;
}

// ── Milestone Template ───────────────────────────────────────

export interface MilestoneTemplate {
  type: MilestoneType;
  title: string;
  description: string;
}

// ── Advance Stage Request ────────────────────────────────────

export interface AdvanceStageRequest {
  notes: string;
}

// ── Timeline Engine Interface ────────────────────────────────

export interface TimelineEngine {
  getTimeline(identityId: string): Promise<FullTimeline>;
  getStages(identityId: string): Promise<StageStatus[]>;
  getStage(identityId: string, stage: IvfStage): Promise<StageStatus | null>;
  advanceStage(identityId: string, notes: string): Promise<StageStatus>;
  getMilestones(identityId: string): Promise<Milestone[]>;
  getMilestone(identityId: string, id: string): Promise<Milestone | null>;
  achieveMilestone(identityId: string, id: string): Promise<Milestone>;
  getEvents(identityId: string): Promise<TimelineEvent[]>;
  getProgress(identityId: string): Promise<ProgressSummary>;
  getExpectedDates(identityId: string): Promise<ExpectedDateInfo[]>;
}

// ── Constants ────────────────────────────────────────────────

export const DEFAULT_STAGE_DURATIONS: Record<IvfStage, number> = {
  [IvfStage.registration]: 7,
  [IvfStage.consultation]: 14,
  [IvfStage.treatment_plan]: 21,
  [IvfStage.ivf_cycle]: 30,
  [IvfStage.retrieval]: 3,
  [IvfStage.transfer]: 14,
  [IvfStage.follow_up]: 30,
  [IvfStage.success]: 0,
};

export const STAGE_LABELS: Record<IvfStage, string> = {
  [IvfStage.registration]: "Registration",
  [IvfStage.consultation]: "Consultation",
  [IvfStage.treatment_plan]: "Treatment Plan",
  [IvfStage.ivf_cycle]: "IVF Cycle",
  [IvfStage.retrieval]: "Egg Retrieval",
  [IvfStage.transfer]: "Embryo Transfer",
  [IvfStage.follow_up]: "Follow-Up",
  [IvfStage.success]: "Success",
};

export const STAGE_TRANSITIONS: Record<IvfStage, IvfStage[]> = {
  [IvfStage.registration]: [IvfStage.consultation],
  [IvfStage.consultation]: [IvfStage.treatment_plan],
  [IvfStage.treatment_plan]: [IvfStage.ivf_cycle],
  [IvfStage.ivf_cycle]: [IvfStage.retrieval],
  [IvfStage.retrieval]: [IvfStage.transfer],
  [IvfStage.transfer]: [IvfStage.follow_up],
  [IvfStage.follow_up]: [IvfStage.success],
  [IvfStage.success]: [],
};

export const STAGE_MILESTONE_TEMPLATES: Record<IvfStage, MilestoneTemplate[]> = {
  [IvfStage.registration]: [
    {
      type: "registration",
      title: "Account Created",
      description: "Your fertility journey profile has been created.",
    },
  ],
  [IvfStage.consultation]: [
    {
      type: "consultation",
      title: "Consultation Scheduled",
      description: "Your initial consultation has been scheduled.",
    },
  ],
  [IvfStage.treatment_plan]: [
    {
      type: "treatment_plan",
      title: "Treatment Plan Established",
      description: "Your personalized treatment plan has been created.",
    },
  ],
  [IvfStage.ivf_cycle]: [
    {
      type: "ivf_cycle_start",
      title: "IVF Cycle Started",
      description: "Your IVF cycle has begun. Medication protocols are active.",
    },
  ],
  [IvfStage.retrieval]: [
    {
      type: "retrieval",
      title: "Egg Retrieval",
      description: "Egg retrieval procedure completed.",
    },
  ],
  [IvfStage.transfer]: [
    {
      type: "transfer",
      title: "Embryo Transfer",
      description: "Embryo transfer procedure completed.",
    },
  ],
  [IvfStage.follow_up]: [
    {
      type: "follow_up",
      title: "Follow-Up Scheduled",
      description: "Post-transfer follow-up appointment scheduled.",
    },
  ],
  [IvfStage.success]: [
    {
      type: "success",
      title: "Treatment Successful",
      description: "Congratulations on your successful treatment outcome.",
    },
  ],
};
