"""
Hermes AI Platform — Shared Types

Defines the core data structures used across platform services.
Compliant with Constitution §1.6 (Modular Design) and §1.9 (Observability by Default).
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


# ─── Enums ─────────────────────────────────────────────────────────────

class DetectionMode(str, Enum):
    """Result of the initial request classification."""
    STRUCTURED = "structured"
    DETERMINISTIC = "deterministic"
    NATURAL_LANGUAGE = "nl"


class ExecutionMode(str, Enum):
    """Which execution pipeline path was taken."""
    MODE1_STRUCTURED = "mode1"
    MODE2_DETERMINISTIC = "mode2"
    MODE3_CLARIFICATION = "mode3"
    MODE4_COMPILATION = "mode4"


class IntentCategory(str, Enum):
    """Classified intent category."""
    UI = "ui"
    BACKEND = "backend"
    INFRASTRUCTURE = "infrastructure"
    SECURITY = "security"
    DOCUMENTATION = "documentation"
    DATABASE = "database"
    DEPLOYMENT = "deployment"
    OPERATIONS = "operations"
    ARCHITECTURE = "architecture"
    FEATURE = "feature"
    BUG = "bug"
    REFACTOR = "refactor"
    UNKNOWN = "unknown"


class RiskLevel(str, Enum):
    """Risk classification for execution gates."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Outcome(str, Enum):
    """Execution outcome per Constitution §1.9."""
    SUCCESS = "success"
    BLOCKED = "blocked"
    FAILED = "failed"
    DEFERRED = "deferred"


# ─── Observability ─────────────────────────────────────────────────────

@dataclass
class TelemetryEnvelope:
    """Mandatory observability fields per Constitution §1.9."""
    service: str
    operation: str
    duration_ms: float
    decision_path: list[str]
    cache_hits: int = 0
    cache_misses: int = 0
    errors: list[str] = field(default_factory=list)
    outcome: Outcome = Outcome.SUCCESS
    clarification_needed: bool = False
    extra: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict."""
        return {
            "service": self.service,
            "operation": self.operation,
            "duration_ms": self.duration_ms,
            "decision_path": self.decision_path,
            "cache_hits": self.cache_hits,
            "cache_misses": self.cache_misses,
            "errors": self.errors,
            "outcome": self.outcome.value,
            "clarification_needed": self.clarification_needed,
            **self.extra,
        }


# ─── Intent Engine Types ───────────────────────────────────────────────

@dataclass
class IntentResult:
    """Result of processing a request through the Intent Engine pipeline.

    This is the primary return type of engine.resolve().
    """
    mode: DetectionMode
    execution_mode: ExecutionMode | None = None
    validation_errors: list[str] = field(default_factory=list)
    clarification: list[str] | None = None
    intent_category: IntentCategory | None = None
    risk_level: RiskLevel | None = None
    execution_plan: dict[str, Any] | None = None
    dry_run: dict[str, Any] | None = None
    telemetry: TelemetryEnvelope | None = None


@dataclass
class ExecutionPlan:
    """Internal execution plan generated by the compiler."""
    goal: str
    project: str | None = None
    repository: str | None = None
    target: str | None = None
    intent_category: IntentCategory = IntentCategory.UNKNOWN
    risk_level: RiskLevel = RiskLevel.LOW
    constraints: dict[str, str] = field(default_factory=dict)
    recommended_actions: list[str] = field(default_factory=list)
    roadmap_item: str | None = None


# ─── PKI Types ─────────────────────────────────────────────────────────

@dataclass
class ProjectInfo:
    name: str
    description: str
    status: str = "active"


@dataclass
class TechnologyInfo:
    framework: str
    language: str
    runtime: str
    package_manager: str


@dataclass
class DocumentationPaths:
    roadmap: str | None = None
    architecture: str | None = None
    operations: str | None = None
    security: str | None = None
    database: str | None = None
    api: str | None = None


@dataclass
class Component:
    name: str
    path: str
    type: str  # "ui", "backend", "infra", "data", "shared"


@dataclass
class OperationsInfo:
    build: str
    test: str
    deployment_targets: list[str] = field(default_factory=lambda: ["production"])
    environments: list[str] = field(default_factory=lambda: ["production", "staging"])


@dataclass
class MetadataInfo:
    version: str
    last_indexed: datetime | str
    active_branch: str


@dataclass
class ProjectIndex:
    """Complete project index entry for a single repository."""
    project: ProjectInfo
    technology: TechnologyInfo
    documentation: DocumentationPaths = field(default_factory=DocumentationPaths)
    components: list[Component] = field(default_factory=list)
    operations: OperationsInfo = field(default_factory=OperationsInfo)
    metadata: MetadataInfo | None = None
    repo_path: str | None = None
    cache_status: str = "fresh"


# ─── Configuration Types ───────────────────────────────────────────────

@dataclass
class IntentEngineConfig:
    """Configuration for the Intent Engine.

    All values have safe defaults. Project-specific overrides are injected
    via config, never hardcoded in platform code.
    """
    structured_patterns: list[str] = field(default_factory=lambda: [
        r"^HERMES EXECUTION",
        r"^⸻",
        r"# HERMES EXECUTION DIRECTIVE",
        r"^---\n[A-Z][A-Z_]+:",
    ])
    deterministic_commands: dict[str, Any] = field(default_factory=dict)
    categories: dict[str, list[str]] = field(default_factory=dict)
    risk_rules: list[dict[str, Any]] = field(default_factory=list)
    latency_budgets_ms: dict[str, dict[str, float]] = field(default_factory=dict)


@dataclass
class ProjectIndexConfig:
    """Configuration for the Project Knowledge Index."""
    workspace_dirs: list[str] = field(default_factory=lambda: ["/home/ubuntu"])
    auto_discover: bool = True
    cache_ttl_l1: int = 3600
    cache_ttl_l2: int = 3600
    max_l1_entries: int = 50
    cooldown_same_trigger: int = 60
    cooldown_diff_trigger: int = 10
    cooldown_full_rescan: int = 300
    git_check_enabled: bool = True
    index_filename: str = ".hermes/project-index.yaml"