#!/bin/bash
# ──────────────────────────────────────────────────────────────────────
# AG Synergy Platform — Deployment Summary Generator
# Type: post-deployment report
# Produces: structured deployment report in docs/releases/
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

HOOK_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$HOOK_DIR"

RELEASE_DIR="docs/releases"
mkdir -p "$RELEASE_DIR"

# ── Gather metadata ──────────────────────────────────────────────────
COMMIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
COMMIT_MSG=$(git log -1 --pretty=%s 2>/dev/null || echo "unknown")
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "v0.0.0-${COMMIT_SHA}")

# ── Run integrity checks (capture pass/fail) ─────────────────────────
check_integrity() {
    bash scripts/repo-integrity-check.sh --allow-dirty 2>&1 || true
}

check_required_files() {
    bash scripts/required-files-check.sh 2>&1 || true
}

check_imports() {
    python3 scripts/import-integrity-check.py --project-root . --exclude artifacts/ lib/ hermes-website/ __tests__ workers/tests-epic0059/ --allow-external 2>&1 || true
}

# ── Build status ─────────────────────────────────────────────────────
if [ -d "artifacts/ags-fertility/dist" ]; then
    BUILD_STATUS="present"
    ASSET_COUNT=$(find artifacts/ags-fertility/dist -type f | wc -l)
    BUILD_SIZE=$(du -sh artifacts/ags-fertility/dist 2>/dev/null | cut -f1)
else
    BUILD_STATUS="missing"
    ASSET_COUNT=0
    BUILD_SIZE="N/A"
fi

# ── Test results ─────────────────────────────────────────────────────
if [ -f "workers/package.json" ]; then
    TEST_OUTPUT=$(cd workers && pnpm vitest run --reporter=json 2>/dev/null || true)
    TEST_PASS=$(echo "$TEST_OUTPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('numPassedTests',0))" 2>/dev/null || echo "0")
    TEST_FAIL=$(echo "$TEST_OUTPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('numFailedTests',0))" 2>/dev/null || echo "0")
    TEST_TOTAL=$(echo "$TEST_OUTPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('numTotalTests',0))" 2>/dev/null || echo "0")
else
    TEST_PASS=0
    TEST_FAIL=0
    TEST_TOTAL=0
fi

# ── Wrangler config ──────────────────────────────────────────────────
ROOT_WRANGLER=$( [ -f "wrangler.jsonc" ] && echo "present" || echo "missing" )
WORKERS_WRANGLER=$( [ -f "workers/wrangler.jsonc" ] && echo "present" || echo "missing" )

# ── Generate report ──────────────────────────────────────────────────
REPORT_FILE="${RELEASE_DIR}/deployment-summary-${COMMIT_SHA}.md"

cat > "$REPORT_FILE" <<EOF
# Deployment Summary

**Version:** ${VERSION}
**Commit:** ${COMMIT_SHA}
**Branch:** ${BRANCH}
**Timestamp:** ${TIMESTAMP}
**Message:** ${COMMIT_MSG}

---

## Integrity Gates

| Gate | Status |
|------|--------|
| Repo Integrity | \`$(check_integrity | grep -c "FAILED" >/dev/null && echo "FAIL" || echo "PASS")\` |
| Required Files | \`$(check_required_files | grep -c "FAILED" >/dev/null && echo "FAIL" || echo "PASS")\` |
| Import Resolution | \`$(check_imports | grep -c "FAILED" >/dev/null && echo "FAIL" || echo "PASS")\` |

## Build Artifacts

| Metric | Value |
|--------|-------|
| Status | ${BUILD_STATUS} |
| Assets | ${ASSET_COUNT} |
| Size | ${BUILD_SIZE} |

## Worker Configs

| Worker | Config |
|--------|--------|
| hermes-website (root) | ${ROOT_WRANGLER} |
| agsynergy-api (workers/) | ${WORKERS_WRANGLER} |

## Tests

| Metric | Value |
|--------|-------|
| Total | ${TEST_TOTAL} |
| Passed | ${TEST_PASS} |
| Failed | ${TEST_FAIL} |

---

*Generated by deployment-summary.sh at ${TIMESTAMP}*
EOF

echo "Report written to: ${REPORT_FILE}"
echo "  Version:  ${VERSION}"
echo "  Commit:   ${COMMIT_SHA}"
echo "  Build:    ${BUILD_STATUS} (${ASSET_COUNT} assets, ${BUILD_SIZE})"
echo "  Tests:    ${TEST_PASS}/${TEST_TOTAL} passed"
echo ""
echo "View: cat ${REPORT_FILE}"